
import React from "react";
import { PDFViewer } from '@react-pdf/renderer';
// import TransactionReceipt from "Receipts/TransactionReceipt";
// import FixedDepositReceipt from "Receipts/FixedDepositReceipt";
// import MovementReceipt from "Receipts/MovementReceipt";
// import TransferReceipt from "Receipts/TransferReceipt";
import MovementTable from "TableExport/MovementTable";

const TestPDF = () => {

  // const Transaction = {
  //   "id": 51,
  //   "clientId": 4,
  //   "fundId": 2,
  //   "stateId": 2,
  //   "shares": 1.4627,
  //   "sharePrice": 1435.7,
  //   "createdAt": "2022-05-19T20:07:42.656Z",
  //   "updatedAt": "2022-06-30T12:37:38.000Z",
  //   "accountAlias": "Matias Podrojsky (4)",
  //   state: "Approved",
  //   fundName:"Real Estate"
  // }

  // const Movement = {
  //   "id": 112,
  //   "accountId": 4,
  //   "stateId": 2,
  //   "transactionId": 75,
  //   "fixedDepositId": null,
  //   "amount": -328.56,
  //   "motive": "STAKE_BUY",
  //   "applied": true,
  //   "createdAt": "2022-07-13T00:07:29.698Z",
  //   "fundId": 4,
  //   "fundName": "Real Estate Fund",
  //   "state": "Approved",
  //   "accountAlias": "Matias Podrojsky (4)"
  // }

  // const Transfer = {
  //   "id": 16,
  //   "senderId": 5,
  //   "receiverId": 4,
  //   "stateId": 1,
  //   "amount": 100,
  //   "createdAt": "2022-06-02T18:21:08.185Z",
  //   "updatedAt": "2022-06-02T18:21:08.185Z",
  //   "senderAlias": "Pamela Guespe (5)",
  //   "receiverAlias": "Matias Podrojsky (4)",
  //   "state": "Pending",
  //   "accountAlias": "Matias Podrojsky (4)",
  //   "incomingTransfer": true,
  //   "AccountId": 4
  // }

  // const FixedDeposit = {
  //   "closed": false,
  //   "id": 47,
  //   "clientId": 35,
  //   "initialAmount": 100,
  //   "interestRate": 8,
  //   "duration": 665,
  //   "startDate": "2021-01-03T00:52:52.000Z",
  //   "endDate": "2022-10-30T00:52:52.000Z",
  //   "stateId": 2,
  //   "createdAt": "2021-01-02T00:52:52.000Z",
  //   "updatedAt": "2022-07-21T21:09:57.076Z",
  //   "accountAlias": "Prueba final Plazo Fijo",
  //   "ActualProfit": {
  //     "fetching": false,
  //     "fetched": false,
  //     "valid": false,
  //     "value": 0
  //   },
  //   "ProfitAtTheEnd": {
  //     "fetching": false,
  //     "fetched": true,
  //     "valid": true,
  //     "value": 114.58
  //   },
  //   "RefundedProfit": {
  //     "fetching": false,
  //     "fetched": false,
  //     "valid": false,
  //     "value": 0
  //   },
  //   "ellapsedDays": 579,
  //   "AnualRate": 8,
  //   "state": {
  //     "bg": "primary",
  //     "text": "Ongoing"
  //   }
  // }

  return (
    <>
      {/*<PDFViewer style={{ width: "100%", height: "100vh" }}><TransactionReceipt Transaction={Transaction} /></PDFViewer>*/}
      <PDFViewer style={{ width: "100%", height: "100vh" }}>
        <MovementTable
          headerInfo={{
            clientName: "Marki Parengo",
            balance: 5000
          }}
          movements={[
            {
              "id": 596,
              "accountId": 1,
              "stateId": 2,
              "userId": null,
              "transactionId": null,
              "fixedDepositId": 107,
              "transferId": null,
              "shareTransferId": null,
              "amount": 5073.97,
              "motive": "FIXED_DEPOSIT_CLOSE",
              "applied": true,
              "createdAt": "2024-07-21T00:00:09.200Z",
              "notes": [],
              "transfer": null,
              "approvedBy": [],
              "partialBalance": 2084006.47
            },
            {
              "id": 593,
              "accountId": 1,
              "stateId": 2,
              "userId": 6,
              "transactionId": 167,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": 2068384,
              "motive": "STAKE_SELL",
              "applied": true,
              "createdAt": "2024-07-15T18:36:57.049Z",
              "notes": [
                {
                  "id": 70,
                  "text": "Liquidación de fondo",
                  "noteType": "FUND_LIQUIDATE",
                  "userName": "Pamela Guespe",
                  "createdAt": "2024-07-15T18:36:57.059Z"
                }
              ],
              "transfer": null,
              "fundId": 5,
              "fundName": "Fund",
              "userName": "Pamela Guespe",
              "approvedBy": [],
              "partialBalance": 2078932.5
            },
            {
              "id": 592,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": 166,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -20683.84,
              "motive": "STAKE_BUY",
              "applied": true,
              "createdAt": "2024-07-15T18:32:04.735Z",
              "notes": [],
              "transfer": null,
              "fundId": 5,
              "fundName": "Fund",
              "userName": "Marki Parengo",
              "approvedBy": [
                "Marki Parengo"
              ],
              "partialBalance": 10548.5
            },
            {
              "id": 584,
              "accountId": 1,
              "stateId": 2,
              "userId": 5,
              "transactionId": 159,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": 2780.78,
              "motive": "STAKE_SELL",
              "applied": true,
              "createdAt": "2024-06-26T19:17:06.614Z",
              "notes": [],
              "transfer": null,
              "fundId": 3,
              "fundName": "Acciones",
              "userName": "Marco Gianga",
              "approvedBy": [],
              "partialBalance": 31232.34
            },
            {
              "id": 541,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": 155,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -1524.38,
              "motive": "STAKE_BUY",
              "applied": true,
              "createdAt": "2024-01-15T13:20:43.595Z",
              "notes": [],
              "transfer": null,
              "fundId": 2,
              "fundName": "Crypto",
              "userName": "Marki Parengo",
              "approvedBy": [
                "Marki Parengo"
              ],
              "partialBalance": 28451.56
            },
            {
              "id": 540,
              "accountId": 1,
              "stateId": 5,
              "userId": 1,
              "transactionId": 154,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": 1342.51,
              "motive": "STAKE_SELL",
              "applied": false,
              "createdAt": "2023-11-14T15:05:58.883Z",
              "notes": [],
              "transfer": null,
              "fundId": 2,
              "fundName": "Crypto",
              "userName": "Marki Parengo",
              "approvedBy": []
            },
            {
              "id": 527,
              "accountId": 1,
              "stateId": 5,
              "userId": 1,
              "transactionId": null,
              "fixedDepositId": 116,
              "transferId": null,
              "shareTransferId": null,
              "amount": -100,
              "motive": "FIXED_DEPOSIT_CREATE",
              "applied": true,
              "createdAt": "2023-09-21T15:31:02.077Z",
              "notes": [],
              "transfer": null,
              "userName": "Marki Parengo",
              "approvedBy": [],
              "partialBalance": 29975.940000000002
            },
            {
              "id": 526,
              "accountId": 1,
              "stateId": 2,
              "userId": 14,
              "transactionId": null,
              "fixedDepositId": 115,
              "transferId": null,
              "shareTransferId": null,
              "amount": -100,
              "motive": "FIXED_DEPOSIT_CREATE",
              "applied": true,
              "createdAt": "2023-09-14T16:51:16.558Z",
              "notes": [],
              "transfer": null,
              "userName": "Marcos Parengo",
              "approvedBy": [
                "Marki Parengo"
              ],
              "partialBalance": 30075.940000000002
            },
            {
              "id": 519,
              "accountId": 1,
              "stateId": 2,
              "userId": null,
              "transactionId": null,
              "fixedDepositId": null,
              "transferId": 70,
              "shareTransferId": null,
              "amount": 75,
              "motive": "TRANSFER_RECEIVE",
              "applied": true,
              "createdAt": "2023-08-31T14:41:05.610Z",
              "notes": [],
              "transfer": {
                "id": 70,
                "senderId": 12,
                "receiverId": 1,
                "stateId": 2,
                "amount": 75,
                "reverted": false,
                "createdAt": "2023-08-31T14:41:05.590Z",
                "updatedAt": "2023-08-31T14:41:05.590Z",
                "sender": {
                  "id": 12,
                  "clientId": 15,
                  "balance": 22.66,
                  "overdraft": 10,
                  "alias": "Marcos 1 Parengo",
                  "createdAt": "2022-06-02T18:22:36.835Z",
                  "updatedAt": "2024-08-03T00:00:09.000Z"
                },
                "receiver": {
                  "id": 1,
                  "clientId": 1,
                  "balance": 2084006.47,
                  "overdraft": 300,
                  "alias": "Marki 3",
                  "createdAt": "2021-11-18T01:05:10.683Z",
                  "updatedAt": "2024-07-21T00:00:09.000Z"
                }
              },
              "approvedBy": [],
              "partialBalance": 30175.940000000002,
              "transferSender": "Marcos 1 Parengo"
            },
            {
              "id": 515,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": null,
              "fixedDepositId": 102,
              "transferId": null,
              "shareTransferId": null,
              "amount": 102.3,
              "motive": "FIXED_DEPOSIT_CLOSE",
              "applied": true,
              "createdAt": "2023-08-17T15:55:00.657Z",
              "notes": [],
              "transfer": null,
              "userName": "Marki Parengo",
              "approvedBy": [],
              "partialBalance": 30100.940000000002
            },
            {
              "id": 478,
              "accountId": 1,
              "stateId": 2,
              "userId": 14,
              "transactionId": null,
              "fixedDepositId": null,
              "transferId": 68,
              "shareTransferId": null,
              "amount": -1,
              "motive": "TRANSFER_SEND",
              "applied": true,
              "createdAt": "2023-07-27T14:16:15.063Z",
              "notes": [],
              "transfer": {
                "id": 68,
                "senderId": 1,
                "receiverId": 27,
                "stateId": 2,
                "amount": 1,
                "reverted": false,
                "createdAt": "2023-07-27T14:16:15.057Z",
                "updatedAt": "2023-07-27T14:16:15.057Z",
                "sender": {
                  "id": 1,
                  "clientId": 1,
                  "balance": 2084006.47,
                  "overdraft": 300,
                  "alias": "Marki 3",
                  "createdAt": "2021-11-18T01:05:10.683Z",
                  "updatedAt": "2024-07-21T00:00:09.000Z"
                },
                "receiver": {
                  "id": 27,
                  "clientId": 32,
                  "balance": 786.87,
                  "overdraft": 0,
                  "alias": "Prueba Plazo",
                  "createdAt": "2022-07-14T03:11:47.778Z",
                  "updatedAt": "2024-06-14T18:29:40.000Z"
                }
              },
              "userName": "Marcos Parengo",
              "approvedBy": [],
              "partialBalance": 29998.640000000003,
              "transferReceiver": "Prueba Plazo"
            },
            {
              "id": 449,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": null,
              "fixedDepositId": 107,
              "transferId": null,
              "shareTransferId": null,
              "amount": -5000,
              "motive": "BID_OFFER",
              "applied": true,
              "createdAt": "2023-07-04T18:49:27.905Z",
              "notes": [],
              "transfer": null,
              "userName": "Marki Parengo",
              "approvedBy": [
                "Marki Parengo",
                "Pamela Guespe"
              ],
              "partialBalance": 29999.640000000003
            },
            {
              "id": 446,
              "accountId": 1,
              "stateId": 2,
              "userId": null,
              "transactionId": null,
              "fixedDepositId": 101,
              "transferId": null,
              "shareTransferId": null,
              "amount": 10.04,
              "motive": "FIXED_DEPOSIT_CLOSE",
              "applied": true,
              "createdAt": "2023-06-30T00:00:09.057Z",
              "notes": [],
              "transfer": null,
              "approvedBy": [],
              "partialBalance": 34999.64
            },
            {
              "id": 445,
              "accountId": 1,
              "stateId": 2,
              "userId": null,
              "transactionId": null,
              "fixedDepositId": 103,
              "transferId": null,
              "shareTransferId": null,
              "amount": 101.97,
              "motive": "FIXED_DEPOSIT_CLOSE",
              "applied": true,
              "createdAt": "2023-06-29T00:00:08.722Z",
              "notes": [],
              "transfer": null,
              "approvedBy": [],
              "partialBalance": 34989.6
            },
            {
              "id": 437,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": 136,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -2000.01,
              "motive": "STAKE_BUY",
              "applied": true,
              "createdAt": "2023-06-08T13:42:11.123Z",
              "notes": [],
              "transfer": null,
              "fundId": 2,
              "fundName": "Crypto",
              "userName": "Marki Parengo",
              "approvedBy": [
                "Marki Parengo"
              ],
              "partialBalance": 34887.63
            },
            {
              "id": 436,
              "accountId": 1,
              "stateId": 2,
              "userId": 14,
              "transactionId": null,
              "fixedDepositId": 106,
              "transferId": null,
              "shareTransferId": null,
              "amount": -10,
              "motive": "BID_OFFER",
              "applied": true,
              "createdAt": "2023-06-02T13:57:21.613Z",
              "notes": [],
              "transfer": null,
              "userName": "Marcos Parengo",
              "approvedBy": [
                "Marki Parengo",
                "Pamela Guespe"
              ],
              "partialBalance": 36887.64
            },
            {
              "id": 419,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": null,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": 10,
              "motive": "DEPOSIT",
              "applied": true,
              "createdAt": "2023-05-11T14:42:00.000Z",
              "notes": [
                {
                  "id": 5,
                  "text": "Nota de deposito",
                  "noteType": "ADMIN_NOTE",
                  "userName": "Marki Parengo",
                  "createdAt": "2023-05-11T14:45:21.274Z"
                }
              ],
              "transfer": null,
              "userName": "Marki Parengo",
              "approvedBy": [
                "Pamela Guespe"
              ],
              "partialBalance": 36897.64
            },
            {
              "id": 408,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": null,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": 10,
              "motive": "DEPOSIT",
              "applied": true,
              "createdAt": "2023-04-20T16:48:00.000Z",
              "notes": [],
              "transfer": null,
              "userName": "Marki Parengo",
              "approvedBy": [
                "Pamela Guespe"
              ],
              "partialBalance": 36887.64
            },
            {
              "id": 406,
              "accountId": 1,
              "stateId": 4,
              "userId": 14,
              "transactionId": null,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -10,
              "motive": "WITHDRAWAL",
              "applied": true,
              "createdAt": "2023-04-20T16:44:24.305Z",
              "notes": [],
              "transfer": null,
              "userName": "Marcos Parengo",
              "approvedBy": [
                "Marki Parengo"
              ],
              "partialBalance": 36877.64
            },
            {
              "id": 405,
              "accountId": 1,
              "stateId": 2,
              "userId": 14,
              "transactionId": 133,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -2000,
              "motive": "STAKE_BUY",
              "applied": true,
              "createdAt": "2023-04-20T14:05:00.763Z",
              "notes": [],
              "transfer": null,
              "fundId": 2,
              "fundName": "Crypto",
              "userName": "Marcos Parengo",
              "approvedBy": [
                "Marki Parengo"
              ],
              "partialBalance": 36887.64
            },
            {
              "id": 404,
              "accountId": 1,
              "stateId": 2,
              "userId": 14,
              "transactionId": null,
              "fixedDepositId": 103,
              "transferId": null,
              "shareTransferId": null,
              "amount": -100,
              "motive": "BID_OFFER",
              "applied": true,
              "createdAt": "2023-03-30T18:37:09.233Z",
              "notes": [],
              "transfer": null,
              "userName": "Marcos Parengo",
              "approvedBy": [
                "Marki Parengo",
                "Marki Parengo"
              ],
              "partialBalance": 38887.64
            },
            {
              "id": 403,
              "accountId": 1,
              "stateId": 2,
              "userId": 14,
              "transactionId": null,
              "fixedDepositId": 102,
              "transferId": null,
              "shareTransferId": null,
              "amount": -100,
              "motive": "FIXED_DEPOSIT_CREATE",
              "applied": true,
              "createdAt": "2023-03-30T17:23:43.227Z",
              "notes": [],
              "transfer": null,
              "userName": "Marcos Parengo",
              "approvedBy": [
                "Marki Parengo"
              ],
              "partialBalance": 38987.64
            },
            {
              "id": 402,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": null,
              "fixedDepositId": 101,
              "transferId": null,
              "shareTransferId": null,
              "amount": -10,
              "motive": "BID_OFFER",
              "applied": true,
              "createdAt": "2023-03-30T14:15:42.764Z",
              "notes": [],
              "transfer": null,
              "userName": "Marki Parengo",
              "approvedBy": [
                "Marki Parengo",
                "Marki Parengo"
              ],
              "partialBalance": 39087.64
            },
            {
              "id": 395,
              "accountId": 1,
              "stateId": 2,
              "userId": 14,
              "transactionId": 131,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -1200,
              "motive": "STAKE_BUY",
              "applied": true,
              "createdAt": "2023-03-09T13:38:27.570Z",
              "notes": [],
              "transfer": null,
              "fundId": 2,
              "fundName": "Crypto",
              "userName": "Marcos Parengo",
              "approvedBy": [
                "Pamela Guespe"
              ],
              "partialBalance": 39097.64
            },
            {
              "id": 394,
              "accountId": 1,
              "stateId": 5,
              "userId": 1,
              "transactionId": 130,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -1200.01,
              "motive": "STAKE_BUY",
              "applied": true,
              "createdAt": "2023-03-08T15:06:50.934Z",
              "notes": [],
              "transfer": null,
              "fundId": 2,
              "fundName": "Crypto",
              "userName": "Marki Parengo",
              "approvedBy": [],
              "partialBalance": 40297.64
            },
            {
              "id": 392,
              "accountId": 1,
              "stateId": 2,
              "userId": 14,
              "transactionId": null,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": 1,
              "motive": "DEPOSIT",
              "applied": true,
              "createdAt": "2023-03-08T13:49:00.000Z",
              "notes": [],
              "transfer": null,
              "userName": "Marcos Parengo",
              "approvedBy": [
                "Marki Parengo"
              ],
              "partialBalance": 41497.65
            },
            {
              "id": 391,
              "accountId": 1,
              "stateId": 2,
              "userId": 14,
              "transactionId": null,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": 100,
              "motive": "DEPOSIT",
              "applied": true,
              "createdAt": "2023-03-08T13:45:00.000Z",
              "notes": [],
              "transfer": null,
              "userName": "Marcos Parengo",
              "approvedBy": [
                "Marki Parengo"
              ],
              "partialBalance": 41496.65
            },
            {
              "id": 390,
              "accountId": 1,
              "stateId": 2,
              "userId": 14,
              "transactionId": 128,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -1300,
              "motive": "STAKE_BUY",
              "applied": true,
              "createdAt": "2023-03-03T18:24:48.580Z",
              "notes": [],
              "transfer": null,
              "fundId": 2,
              "fundName": "Crypto",
              "userName": "Marcos Parengo",
              "approvedBy": [
                "Marki Parengo"
              ],
              "partialBalance": 41396.65
            },
            {
              "id": 389,
              "accountId": 1,
              "stateId": 2,
              "userId": 14,
              "transactionId": 127,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": 1198.18,
              "motive": "STAKE_SELL",
              "applied": true,
              "createdAt": "2023-03-03T18:23:26.838Z",
              "notes": [],
              "transfer": null,
              "fundId": 2,
              "fundName": "Crypto",
              "userName": "Marcos Parengo",
              "approvedBy": [
                "Marki Parengo"
              ],
              "partialBalance": 42696.65
            },
            {
              "id": 388,
              "accountId": 1,
              "stateId": 2,
              "userId": 14,
              "transactionId": 126,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -2000,
              "motive": "STAKE_BUY",
              "applied": true,
              "createdAt": "2023-03-03T18:22:37.094Z",
              "notes": [],
              "transfer": null,
              "fundId": 2,
              "fundName": "Crypto",
              "userName": "Marcos Parengo",
              "approvedBy": [
                "Marki Parengo"
              ],
              "partialBalance": 41498.47
            },
            {
              "id": 387,
              "accountId": 1,
              "stateId": 2,
              "userId": 14,
              "transactionId": 125,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": 1198.18,
              "motive": "STAKE_SELL",
              "applied": true,
              "createdAt": "2023-03-03T18:17:46.458Z",
              "notes": [],
              "transfer": null,
              "fundId": 2,
              "fundName": "Crypto",
              "userName": "Marcos Parengo",
              "approvedBy": [
                "Marki Parengo"
              ],
              "partialBalance": 43498.47
            },
            {
              "id": 384,
              "accountId": 1,
              "stateId": 4,
              "userId": 14,
              "transactionId": null,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -400,
              "motive": "WITHDRAWAL",
              "applied": true,
              "createdAt": "2023-03-03T18:01:59.501Z",
              "notes": [],
              "transfer": null,
              "userName": "Marcos Parengo",
              "approvedBy": [
                "Marki Parengo"
              ],
              "partialBalance": 42300.29
            },
            {
              "id": 350,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": null,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": 1000,
              "motive": "DEPOSIT",
              "applied": true,
              "createdAt": "2023-02-09T14:16:00.000Z",
              "notes": [],
              "transfer": null,
              "userName": "Marki Parengo",
              "approvedBy": [
                "Pamela Guespe"
              ],
              "partialBalance": 42700.29
            },
            {
              "id": 349,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": 117,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -2000,
              "motive": "STAKE_BUY",
              "applied": true,
              "createdAt": "2023-02-02T14:26:03.243Z",
              "notes": [],
              "transfer": null,
              "fundId": 2,
              "fundName": "Crypto",
              "userName": "Marki Parengo",
              "approvedBy": [
                "Marco Gianga"
              ],
              "partialBalance": 41700.29
            },
            {
              "id": 331,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": 110,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": 1310.6,
              "motive": "STAKE_SELL",
              "applied": true,
              "createdAt": "2023-01-24T21:45:40.837Z",
              "notes": [],
              "transfer": null,
              "fundId": 2,
              "fundName": "Crypto",
              "userName": "Marki Parengo",
              "approvedBy": [],
              "partialBalance": 43700.29
            },
            {
              "id": 330,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": 109,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -2000,
              "motive": "STAKE_BUY",
              "applied": true,
              "createdAt": "2023-01-24T21:40:27.816Z",
              "notes": [],
              "transfer": null,
              "fundId": 2,
              "fundName": "Crypto",
              "userName": "Marki Parengo",
              "approvedBy": [],
              "partialBalance": 42389.69
            },
            {
              "id": 329,
              "accountId": 1,
              "stateId": 5,
              "userId": 1,
              "transactionId": 108,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -1400,
              "motive": "STAKE_BUY",
              "applied": true,
              "createdAt": "2023-01-24T21:36:01.321Z",
              "notes": [],
              "transfer": null,
              "fundId": 2,
              "fundName": "Crypto",
              "userName": "Marki Parengo",
              "approvedBy": [],
              "partialBalance": 44389.69
            },
            {
              "id": 317,
              "accountId": 1,
              "stateId": 5,
              "userId": 14,
              "transactionId": null,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -10,
              "motive": "WITHDRAWAL",
              "applied": true,
              "createdAt": "2023-01-20T16:05:41.840Z",
              "notes": [],
              "transfer": null,
              "userName": "Marcos Parengo",
              "approvedBy": [],
              "partialBalance": 45789.69
            },
            {
              "id": 316,
              "accountId": 1,
              "stateId": 5,
              "userId": 1,
              "transactionId": 106,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": 1212.06,
              "motive": "STAKE_SELL",
              "applied": false,
              "createdAt": "2023-01-20T15:39:06.538Z",
              "notes": [],
              "transfer": null,
              "fundId": 2,
              "fundName": "Crypto",
              "userName": "Marki Parengo",
              "approvedBy": []
            },
            {
              "id": 301,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": 105,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -1500,
              "motive": "STAKE_BUY",
              "applied": true,
              "createdAt": "2023-01-06T18:08:33.765Z",
              "notes": [],
              "transfer": null,
              "fundId": 2,
              "fundName": "Crypto",
              "userName": "Marki Parengo",
              "approvedBy": [],
              "partialBalance": 45799.69
            },
            {
              "id": 300,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": 104,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -1299.99,
              "motive": "STAKE_BUY",
              "applied": true,
              "createdAt": "2023-01-05T16:54:01.875Z",
              "notes": [],
              "transfer": null,
              "fundId": 2,
              "fundName": "Crypto",
              "userName": "Marki Parengo",
              "approvedBy": [
                "Marki Parengo"
              ],
              "partialBalance": 47299.69
            },
            {
              "id": 298,
              "accountId": 1,
              "stateId": 5,
              "userId": 14,
              "transactionId": 102,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -1500,
              "motive": "STAKE_BUY",
              "applied": true,
              "createdAt": "2023-01-05T16:49:49.370Z",
              "notes": [],
              "transfer": null,
              "fundId": 2,
              "fundName": "Crypto",
              "userName": "Marcos Parengo",
              "approvedBy": [],
              "partialBalance": 48599.68
            },
            {
              "id": 297,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": 101,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -1500,
              "motive": "STAKE_BUY",
              "applied": true,
              "createdAt": "2023-01-05T15:04:20.824Z",
              "notes": [],
              "transfer": null,
              "fundId": 2,
              "fundName": "Crypto",
              "userName": "Marki Parengo",
              "approvedBy": [
                "Marki Parengo"
              ],
              "partialBalance": 50099.68
            },
            {
              "id": 296,
              "accountId": 1,
              "stateId": 4,
              "userId": 14,
              "transactionId": null,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -100,
              "motive": "WITHDRAWAL",
              "applied": true,
              "createdAt": "2023-01-05T15:00:25.078Z",
              "notes": [],
              "transfer": null,
              "userName": "Marcos Parengo",
              "approvedBy": [
                "Marki Parengo"
              ],
              "partialBalance": 51599.68
            },
            {
              "id": 295,
              "accountId": 1,
              "stateId": 2,
              "userId": 14,
              "transactionId": 100,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -1000,
              "motive": "STAKE_BUY",
              "applied": true,
              "createdAt": "2023-01-05T14:59:56.293Z",
              "notes": [],
              "transfer": null,
              "fundId": 3,
              "fundName": "Acciones",
              "userName": "Marcos Parengo",
              "approvedBy": [
                "Marki Parengo"
              ],
              "partialBalance": 51699.68
            },
            {
              "id": 294,
              "accountId": 1,
              "stateId": 2,
              "userId": 14,
              "transactionId": 99,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -1000,
              "motive": "STAKE_BUY",
              "applied": true,
              "createdAt": "2023-01-05T14:59:21.533Z",
              "notes": [],
              "transfer": null,
              "fundId": 3,
              "fundName": "Acciones",
              "userName": "Marcos Parengo",
              "approvedBy": [
                "Marki Parengo"
              ],
              "partialBalance": 52699.68
            },
            {
              "id": 292,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": null,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": 10,
              "motive": "DEPOSIT",
              "applied": true,
              "createdAt": "2022-12-15T18:37:00.000Z",
              "notes": [],
              "transfer": null,
              "userName": "Marki Parengo",
              "approvedBy": [],
              "partialBalance": 53699.68
            },
            {
              "id": 291,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": null,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": 1,
              "motive": "DEPOSIT",
              "applied": true,
              "createdAt": "2022-12-15T18:33:00.000Z",
              "notes": [],
              "transfer": null,
              "userName": "Marki Parengo",
              "approvedBy": [
                "Pamela Guespe"
              ],
              "partialBalance": 53689.68
            },
            {
              "id": 290,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": null,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": 1,
              "motive": "DEPOSIT",
              "applied": true,
              "createdAt": "2022-12-15T17:29:00.000Z",
              "notes": [],
              "transfer": null,
              "userName": "Marki Parengo",
              "approvedBy": [
                "Pamela Guespe"
              ],
              "partialBalance": 53688.68
            },
            {
              "id": 289,
              "accountId": 1,
              "stateId": 2,
              "userId": 14,
              "transactionId": null,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": 10,
              "motive": "DEPOSIT",
              "applied": true,
              "createdAt": "2022-12-15T14:38:00.000Z",
              "notes": [],
              "transfer": null,
              "userName": "Marcos Parengo",
              "approvedBy": [],
              "partialBalance": 53687.68
            },
            {
              "id": 288,
              "accountId": 1,
              "stateId": 2,
              "userId": 14,
              "transactionId": null,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": 10,
              "motive": "DEPOSIT",
              "applied": true,
              "createdAt": "2022-12-15T14:11:00.000Z",
              "notes": [],
              "transfer": null,
              "userName": "Marcos Parengo",
              "approvedBy": [],
              "partialBalance": 53677.68
            },
            {
              "id": 287,
              "accountId": 1,
              "stateId": 2,
              "userId": 11,
              "transactionId": null,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": 10,
              "motive": "DEPOSIT",
              "applied": true,
              "createdAt": "2022-12-15T14:08:00.000Z",
              "notes": [],
              "transfer": null,
              "userName": "Marki Parengo",
              "approvedBy": [],
              "partialBalance": 53667.68
            },
            {
              "id": 286,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": null,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": 10,
              "motive": "DEPOSIT",
              "applied": true,
              "createdAt": "2022-12-15T13:52:00.000Z",
              "notes": [],
              "transfer": null,
              "userName": "Marki Parengo",
              "approvedBy": [],
              "partialBalance": 53657.68
            },
            {
              "id": 280,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": null,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -10000,
              "motive": "WITHDRAWAL",
              "applied": true,
              "createdAt": "2022-10-13T13:20:00.000Z",
              "notes": [],
              "transfer": null,
              "userName": "Marki Parengo",
              "approvedBy": [],
              "partialBalance": 53647.68
            },
            {
              "id": 279,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": null,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": 10000,
              "motive": "DEPOSIT",
              "applied": true,
              "createdAt": "2022-10-13T13:20:00.000Z",
              "notes": [],
              "transfer": null,
              "userName": "Marki Parengo",
              "approvedBy": [],
              "partialBalance": 63647.68
            },
            {
              "id": 278,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": null,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -10000,
              "motive": "WITHDRAWAL",
              "applied": true,
              "createdAt": "2022-10-13T13:18:00.000Z",
              "notes": [],
              "transfer": null,
              "userName": "Marki Parengo",
              "approvedBy": [],
              "partialBalance": 53647.68
            },
            {
              "id": 262,
              "accountId": 1,
              "stateId": 4,
              "userId": 1,
              "transactionId": null,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -1,
              "motive": "WITHDRAWAL",
              "applied": true,
              "createdAt": "2022-09-26T10:27:00.000Z",
              "notes": [],
              "transfer": null,
              "userName": "Marki Parengo",
              "approvedBy": [],
              "partialBalance": 63647.68
            },
            {
              "id": 261,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": 84,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -2000,
              "motive": "STAKE_BUY",
              "applied": true,
              "createdAt": "2022-09-23T21:30:46.958Z",
              "notes": [],
              "transfer": null,
              "fundId": 2,
              "fundName": "Crypto",
              "userName": "Marki Parengo",
              "approvedBy": [
                "Marki Parengo"
              ],
              "partialBalance": 63648.68
            },
            {
              "id": 260,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": 83,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": 438.87,
              "motive": "STAKE_SELL",
              "applied": true,
              "createdAt": "2022-09-23T20:16:28.935Z",
              "notes": [],
              "transfer": null,
              "fundId": 4,
              "fundName": "Real Estate Fund",
              "userName": "Marki Parengo",
              "approvedBy": [],
              "partialBalance": 65648.68
            },
            {
              "id": 259,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": 82,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -32015.97,
              "motive": "STAKE_BUY",
              "applied": true,
              "createdAt": "2022-09-23T20:14:17.843Z",
              "notes": [],
              "transfer": null,
              "fundId": 4,
              "fundName": "Real Estate Fund",
              "userName": "Marki Parengo",
              "approvedBy": [],
              "partialBalance": 65209.80999999999
            },
            {
              "id": 258,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": null,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": 100000,
              "motive": "DEPOSIT",
              "applied": true,
              "createdAt": "2022-09-23T20:13:00.000Z",
              "notes": [],
              "transfer": null,
              "userName": "Marki Parengo",
              "approvedBy": [],
              "partialBalance": 97225.78
            },
            {
              "id": 257,
              "accountId": 1,
              "stateId": 4,
              "userId": 1,
              "transactionId": null,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -20.5,
              "motive": "WITHDRAWAL",
              "applied": true,
              "createdAt": "2022-09-22T23:52:00.000Z",
              "notes": [],
              "transfer": null,
              "userName": "Marki Parengo",
              "approvedBy": [],
              "partialBalance": -2774.220000000001
            },
            {
              "id": 254,
              "accountId": 1,
              "stateId": 2,
              "userId": 1,
              "transactionId": 81,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": 1850.28,
              "motive": "STAKE_SELL",
              "applied": true,
              "createdAt": "2022-09-22T23:34:40.320Z",
              "notes": [],
              "transfer": null,
              "fundId": 2,
              "fundName": "Crypto",
              "userName": "Marki Parengo",
              "approvedBy": [],
              "partialBalance": -2753.720000000001
            },
            {
              "id": 161,
              "accountId": 1,
              "stateId": 2,
              "userId": null,
              "transactionId": 77,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -2000,
              "motive": "STAKE_BUY",
              "applied": true,
              "createdAt": "2022-08-23T20:40:56.067Z",
              "notes": [],
              "transfer": null,
              "fundId": 2,
              "fundName": "Crypto",
              "approvedBy": [
                "Pamela Guespe"
              ],
              "partialBalance": -4604.000000000001
            },
            {
              "id": 66,
              "accountId": 1,
              "stateId": 2,
              "userId": null,
              "transactionId": 57,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": -400,
              "motive": "STAKE_BUY",
              "applied": true,
              "createdAt": "2022-05-19T21:11:07.898Z",
              "notes": [],
              "transfer": null,
              "fundId": 4,
              "fundName": "Real Estate Fund",
              "approvedBy": [],
              "partialBalance": -2604.000000000001
            },
            {
              "id": 57,
              "accountId": 1,
              "stateId": 2,
              "userId": null,
              "transactionId": null,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": 100,
              "motive": "DEPOSIT",
              "applied": true,
              "createdAt": "2022-05-19T19:44:00.000Z",
              "notes": [],
              "transfer": null,
              "approvedBy": [],
              "partialBalance": -2204.000000000001
            },
            {
              "id": 14,
              "accountId": 1,
              "stateId": 2,
              "userId": null,
              "transactionId": null,
              "fixedDepositId": null,
              "transferId": null,
              "shareTransferId": null,
              "amount": 1000,
              "motive": "DEPOSIT",
              "applied": true,
              "createdAt": "2022-02-01T01:19:25.192Z",
              "notes": [],
              "transfer": null,
              "approvedBy": [],
              "partialBalance": -2304.000000000001
            }
          ]}
        />
      </PDFViewer>
      {/*<PDFViewer style={{ width: "100%", height: "100vh" }}><MovementReceipt Movement={Movement} /></PDFViewer>*/}
      {/* <PDFViewer style={{ width: "100%", height: "100vh" }}>  <TransferReceipt Transfer={Transfer} /></PDFViewer>*/}
    </>
  );
}

export default TestPDF
